package org.example.enums;

public enum StudentComparators {
    STUDENT_COMPARATOR_AVG_EXAM_SCORE,
    STUDENT_COMPARATOR_CURRENT_COURSE_NUMBER,
    STUDENT_COMPARATOR_FULL_NAME,
    STUDENT_COMPARATOR_UNIVERSITY_ID

}
