package org.example.enums;

public enum UniversityComparators {
    UNIVERSITY_COMPARATOR_FULL_NAME,
    UNIVERSITY_COMPARATOR_ID,
    UNIVERSITY_COMPARATOR_MAINPROFILE,
    UNIVERSITY_COMPARATOR_SHORTNAME,
    UNIVERSITY_COMPARATOR_YEAR_OF_FOUNDATION
}
